import type { University, Program, Institute } from './types';

export const UNIVERSITIES: University[] = [
  { id:1,  abbr:'UM',        name:'Universiti Malaya',                           type:'public',         location:'Kuala Lumpur',               qs_ranking:65,  color:'#003580', domain:'um.edu.my',            website:'https://www.um.edu.my',           description:"Malaysia's oldest and most prestigious university, ranked #1 nationally with 309-acre campus and world-class research facilities.", tuition_min:20000, tuition_max:55000, established:1949, students_count:22000 },
  { id:2,  abbr:'USM',       name:'Universiti Sains Malaysia',                   type:'public',         location:'Penang',                     qs_ranking:134, color:'#00539C', domain:'usm.my',               website:'https://www.usm.my',              description:"A leading research university on scenic Penang island, excelling in science, technology, and health sciences.", tuition_min:18000, tuition_max:45000, established:1969, students_count:28000 },
  { id:3,  abbr:'UPM',       name:'Universiti Putra Malaysia',                   type:'public',         location:'Serdang, Selangor',           qs_ranking:130, color:'#006633', domain:'upm.edu.my',           website:'https://www.upm.edu.my',          description:"Globally recognised for agriculture, environmental sciences, and engineering — with a stunning 1,200-acre campus.", tuition_min:18000, tuition_max:42000, established:1971, students_count:27000 },
  { id:4,  abbr:'UTM',       name:'Universiti Teknologi Malaysia',               type:'public',         location:'Johor Bahru',                 qs_ranking:189, color:'#003087', domain:'utm.my',               website:'https://www.utm.my',              description:"Malaysia's leading engineering and technology university with campuses in Johor Bahru and Kuala Lumpur.", tuition_min:17000, tuition_max:40000, established:1904, students_count:27000 },
  { id:5,  abbr:'UKM',       name:'Universiti Kebangsaan Malaysia',              type:'public',         location:'Bangi, Selangor',             qs_ranking:163, color:'#800020', domain:'ukm.my',               website:'https://www.ukm.my',              description:"Malaysia's national university, renowned for its medical faculty, law school, and broad research excellence.", tuition_min:18000, tuition_max:50000, established:1970, students_count:27000 },
  { id:6,  abbr:'UITM',      name:'Universiti Teknologi MARA',                   type:'public',         location:'Shah Alam, Selangor',         qs_ranking:null,color:'#8B0000', domain:'uitm.edu.my',          website:'https://www.uitm.edu.my',         description:"Malaysia's largest university with 35+ campuses nationwide, offering the widest range of professional programmes.", tuition_min:8000,  tuition_max:25000, established:1956, students_count:170000 },
  { id:7,  abbr:'UNITEN',    name:'Universiti Tenaga Nasional',                  type:'public',         location:'Kajang, Selangor',            qs_ranking:null,color:'#1A237E', domain:'uniten.edu.my',        website:'https://www.uniten.edu.my',       description:"An energy-focused technical university backed by Tenaga Nasional Berhad (TNB), Malaysia's national utility company.", tuition_min:15000, tuition_max:35000, established:1994, students_count:8000 },
  { id:8,  abbr:'UMPSA',     name:'Universiti Malaysia Pahang Al-Sultan Abdullah',type:'public',        location:'Gambang, Pahang',             qs_ranking:null,color:'#006400', domain:'ump.edu.my',           website:'https://www.ump.edu.my',          description:"A technical university excelling in engineering, manufacturing, and automotive programmes in the heart of Pahang.", tuition_min:10000, tuition_max:28000, established:2002, students_count:10000 },
  { id:9,  abbr:'MMU',       name:'Multimedia University',                       type:'private',        location:'Cyberjaya',                   qs_ranking:null,color:'#1A4FA0', domain:'mmu.edu.my',           website:'https://www.mmu.edu.my',          description:"Malaysia's first private university, specialising in technology, engineering, and creative multimedia in the Multimedia Super Corridor.", tuition_min:22000, tuition_max:38000, established:1999, students_count:14000 },
  { id:10, abbr:'APU',       name:'Asia Pacific University',                     type:'private',        location:'Bukit Jalil, Kuala Lumpur',   qs_ranking:null,color:'#C8102E', domain:'apu.edu.my',           website:'https://www.apu.edu.my',          description:"A top private tech-focused university with UK-validated degrees and students from 130+ countries — strong industry partnerships.", tuition_min:24000, tuition_max:42000, established:1993, students_count:14000 },
  { id:11, abbr:'UTAR',      name:'Universiti Tunku Abdul Rahman',               type:'private',        location:'Kampar, Perak',               qs_ranking:null,color:'#E31837', domain:'utar.edu.my',          website:'https://www.utar.edu.my',         description:"A non-profit private university offering affordable, high-quality education — consistently ranked among Malaysia's top private institutions.", tuition_min:15000, tuition_max:32000, established:2002, students_count:22000 },
  { id:12, abbr:"TAYLOR'S",  name:"Taylor's University",                         type:'private',        location:'Subang Jaya, Selangor',       qs_ranking:null,color:'#1B3A6B', domain:'taylors.edu.my',       website:'https://www.taylors.edu.my',      description:"Top 3 private university in Malaysia — renowned for hospitality, law, business, and the American Degree Transfer Program.", tuition_min:28000, tuition_max:55000, established:1969, students_count:17000 },
  { id:13, abbr:'SUNWAY',    name:'Sunway University',                           type:'private',        location:'Subang Jaya, Selangor',       qs_ranking:null,color:'#E87722', domain:'sunway.edu.my',        website:'https://www.sunway.edu.my',       description:"A leading private university affiliated with Lancaster University UK, with strong business, medicine, and arts programmes.", tuition_min:25000, tuition_max:50000, established:1987, students_count:10000 },
  { id:14, abbr:'UNITAR',    name:'UNITAR International University',             type:'private',        location:'Kelana Jaya, Selangor',       qs_ranking:null,color:'#6D28D9', domain:'unitar.my',            website:'https://www.unitar.my',           description:"Malaysia's first fully online university, offering flexible post-graduate and professional programmes for working adults.", tuition_min:12000, tuition_max:28000, established:1997, students_count:8000 },
  { id:15, abbr:'INTI',      name:'INTI International University',               type:'private',        location:'Nilai, Negeri Sembilan',      qs_ranking:null,color:'#D32F2F', domain:'newinti.edu.my',       website:'https://www.newinti.edu.my',      description:"Part of the Laureate International Universities network — dual-award degrees with partners in Australia, UK, and the US.", tuition_min:18000, tuition_max:40000, established:1986, students_count:15000 },
  { id:16, abbr:'HELP',      name:'HELP University',                             type:'private',        location:'Kuala Lumpur',                qs_ranking:null,color:'#1565C0', domain:'help.edu.my',          website:'https://www.help.edu.my',         description:"Pioneer in psychology and law education in Malaysia, with strong twinning programmes at prestigious global universities.", tuition_min:18000, tuition_max:38000, established:1986, students_count:7000 },
  { id:17, abbr:'LINCOLN',   name:'Lincoln University College',                  type:'private',        location:'Petaling Jaya, Selangor',     qs_ranking:null,color:'#8B0000', domain:'lincoln.edu.my',       website:'https://www.lincoln.edu.my',      description:"An innovative private university offering a wide range of professional programmes — known for strong medicine and health sciences.", tuition_min:15000, tuition_max:35000, established:2002, students_count:8000 },
  { id:18, abbr:'MAHSA',     name:'MAHSA University',                            type:'private',        location:'Bandar Saujana Putra, Selangor',qs_ranking:null,color:'#0D47A1',domain:'mahsa.edu.my',         website:'https://www.mahsa.edu.my',        description:"A health sciences-focused university with comprehensive medical, dental, pharmacy, and nursing programmes.", tuition_min:18000, tuition_max:45000, established:2005, students_count:6000 },
  { id:19, abbr:'CYBERJAYA', name:'University of Cyberjaya',                     type:'private',        location:'Cyberjaya, Selangor',         qs_ranking:null,color:'#00796B', domain:'unicyberjaya.edu.my',  website:'https://www.unicyberjaya.edu.my', description:"A health and technology-focused university in the heart of Malaysia's Silicon Valley — Cyberjaya.", tuition_min:15000, tuition_max:38000, established:2005, students_count:5000 },
  { id:20, abbr:'IUKL',      name:'Infrastructure University Kuala Lumpur',      type:'private',        location:'Kajang, Selangor',            qs_ranking:null,color:'#F57F17', domain:'iukl.edu.my',          website:'https://www.iukl.edu.my',         description:"A specialised university focused on engineering, architecture, and infrastructure with strong industry-linked programmes.", tuition_min:14000, tuition_max:30000, established:1999, students_count:5000 },
  { id:21, abbr:'CITY',      name:'City University Malaysia',                    type:'private',        location:'Petaling Jaya, Selangor',     qs_ranking:null,color:'#311B92', domain:'city.edu.my',          website:'https://www.city.edu.my',         description:"A private university offering professional programmes in business, law, engineering, and creative arts.", tuition_min:13000, tuition_max:28000, established:1984, students_count:5000 },
  { id:22, abbr:'NILAI',     name:'Nilai University',                            type:'private',        location:'Nilai, Negeri Sembilan',      qs_ranking:null,color:'#BF360C', domain:'nilai.edu.my',         website:'https://www.nilai.edu.my',        description:"A comprehensive private university offering a diverse range of programmes from foundation to postgraduate level.", tuition_min:12000, tuition_max:30000, established:1997, students_count:6000 },
  { id:23, abbr:'SEGI',      name:'SEGi University',                             type:'private',        location:'Kota Damansara, Selangor',    qs_ranking:null,color:'#880E4F', domain:'segi.edu.my',          website:'https://www.segi.edu.my',         description:"One of Malaysia's largest private universities with campuses nationwide — strong focus on medicine, dentistry, and business.", tuition_min:14000, tuition_max:35000, established:1977, students_count:20000 },
  { id:24, abbr:'UNICAM',    name:'University College of Aviation Malaysia',     type:'private',        location:'Subang, Selangor',            qs_ranking:null,color:'#01579B', domain:'unicam.edu.my',        website:'https://www.unicam.edu.my',       description:"Malaysia's premier aviation university — the only institution offering a fully integrated aviation degree with real flight training.", tuition_min:25000, tuition_max:55000, established:2007, students_count:2000 },
  { id:25, abbr:'GEOMATIKA', name:'Geomatika University College',                type:'private',        location:'Kuala Lumpur',                qs_ranking:null,color:'#2E7D32', domain:'geomatika.edu.my',     website:'https://www.geomatika.edu.my',    description:"Specialised in geoinformation, surveying, urban planning, and environmental management — unique in Malaysia.", tuition_min:12000, tuition_max:25000, established:1997, students_count:2000 },
  { id:26, abbr:'HWU',       name:'Heriot-Watt University Malaysia',             type:'foreign_branch', location:'Putrajaya',                   qs_ranking:301, color:'#7B1FA2', domain:'hw.ac.uk',             website:'https://www.hw.ac.uk/malaysia',   description:"The Malaysian campus of Scotland's prestigious Heriot-Watt University — earn a UK degree in Malaysia at a fraction of UK costs.", tuition_min:35000, tuition_max:60000, established:2014, students_count:4000 },
];

export const PROGRAMS: Program[] = [
  { id:1,  university_id:1,  name:'Bachelor of Computer Science',          level:'bachelor', duration_years:3, tuition_per_year:22000, field:'Technology',    description:'Comprehensive CS covering AI, systems, networks and software engineering.',                            intake:'Feb, Jul',     university_name:'Universiti Malaya',           university_abbr:'UM',        university_location:'Kuala Lumpur' },
  { id:2,  university_id:1,  name:'Bachelor of Medicine (MBBS)',           level:'bachelor', duration_years:5, tuition_per_year:52000, field:'Medicine',      description:"One of Asia's most respected medical degrees, fully accredited by the Malaysian Medical Council.",    intake:'Feb',          university_name:'Universiti Malaya',           university_abbr:'UM',        university_location:'Kuala Lumpur' },
  { id:3,  university_id:1,  name:'Bachelor of Engineering (Electrical)',  level:'bachelor', duration_years:4, tuition_per_year:25000, field:'Engineering',   description:'Rigorous electrical engineering with strong industry partnerships.',                                 intake:'Feb, Sep',     university_name:'Universiti Malaya',           university_abbr:'UM',        university_location:'Kuala Lumpur' },
  { id:4,  university_id:1,  name:'Master of Business Administration',     level:'master',   duration_years:1.5,tuition_per_year:28000, field:'Business',     description:'Full-time and part-time MBA for professionals accelerating their careers.',                          intake:'Feb, Jul',     university_name:'Universiti Malaya',           university_abbr:'UM',        university_location:'Kuala Lumpur' },
  { id:5,  university_id:1,  name:'Bachelor of Laws (LLB)',                level:'bachelor', duration_years:3, tuition_per_year:24000, field:'Law',           description:'Internationally recognised law degree with mooting competitions and a strong alumni network.',       intake:'Feb',          university_name:'Universiti Malaya',           university_abbr:'UM',        university_location:'Kuala Lumpur' },
  { id:6,  university_id:2,  name:'Bachelor of Computer Science',          level:'bachelor', duration_years:3, tuition_per_year:19000, field:'Technology',    description:'Strong foundation with electives in AI, cybersecurity and data science.',                           intake:'Feb, Jul',     university_name:'Universiti Sains Malaysia',   university_abbr:'USM',       university_location:'Penang' },
  { id:7,  university_id:2,  name:'Bachelor of Pharmacy',                  level:'bachelor', duration_years:4, tuition_per_year:26000, field:'Medicine',      description:'Fully accredited pharmacy programme recognised across ASEAN and the Middle East.',                  intake:'Feb',          university_name:'Universiti Sains Malaysia',   university_abbr:'USM',       university_location:'Penang' },
  { id:8,  university_id:2,  name:'Bachelor of Engineering (Mechanical)',  level:'bachelor', duration_years:4, tuition_per_year:21000, field:'Engineering',   description:'Thermal, manufacturing, and materials streams with modern lab facilities.',                         intake:'Feb, Jul',     university_name:'Universiti Sains Malaysia',   university_abbr:'USM',       university_location:'Penang' },
  { id:9,  university_id:3,  name:'Bachelor of Computer Science',          level:'bachelor', duration_years:4, tuition_per_year:19000, field:'Technology',    description:"Research-oriented CS degree with access to UPM's high-performance computing lab.",                 intake:'Sep',          university_name:'Universiti Putra Malaysia',   university_abbr:'UPM',       university_location:'Serdang, Selangor' },
  { id:10, university_id:3,  name:'Bachelor of Agricultural Science',      level:'bachelor', duration_years:4, tuition_per_year:18000, field:'Science',       description:"World-class agri-science programme underpinned by UPM's 1,200-acre working farm.",               intake:'Sep',          university_name:'Universiti Putra Malaysia',   university_abbr:'UPM',       university_location:'Serdang, Selangor' },
  { id:11, university_id:4,  name:'Bachelor of Electrical Engineering',    level:'bachelor', duration_years:4, tuition_per_year:20000, field:'Engineering',   description:'Power systems, electronics, and telecommunications in a fully equipped lab.',                       intake:'Feb, Sep',     university_name:'Universiti Teknologi Malaysia',university_abbr:'UTM',      university_location:'Johor Bahru' },
  { id:12, university_id:4,  name:'Bachelor of Civil Engineering',         level:'bachelor', duration_years:4, tuition_per_year:20000, field:'Engineering',   description:'Structures, geotechnics, and hydraulics — shaping the infrastructure of tomorrow.',               intake:'Feb, Sep',     university_name:'Universiti Teknologi Malaysia',university_abbr:'UTM',      university_location:'Johor Bahru' },
  { id:13, university_id:5,  name:'Bachelor of Medicine (MBBS)',           level:'bachelor', duration_years:5, tuition_per_year:48000, field:'Medicine',      description:'UKM Medical Faculty is one of the most respected in Southeast Asia with an on-campus teaching hospital.', intake:'Feb', university_name:'Universiti Kebangsaan Malaysia',university_abbr:'UKM',   university_location:'Bangi, Selangor' },
  { id:14, university_id:9,  name:'Bachelor of Computer Science (AI)',     level:'bachelor', duration_years:3, tuition_per_year:24000, field:'Technology',    description:'Specialised AI curriculum with deep learning, computer vision, and NLP modules.',                   intake:'Feb, Jul, Sep',university_name:'Multimedia University',        university_abbr:'MMU',       university_location:'Cyberjaya' },
  { id:15, university_id:9,  name:'Bachelor of Multimedia Design',         level:'bachelor', duration_years:3, tuition_per_year:23000, field:'Arts & Design', description:'Creative programme blending graphic design, motion graphics, UX, and digital storytelling.',        intake:'Feb, Jul, Sep',university_name:'Multimedia University',        university_abbr:'MMU',       university_location:'Cyberjaya' },
  { id:16, university_id:10, name:'Bachelor of Software Engineering',      level:'bachelor', duration_years:3, tuition_per_year:26000, field:'Technology',    description:'UK-validated degree with agile methodology, DevOps, and enterprise software tracks.',              intake:'Feb, Jul, Sep',university_name:'Asia Pacific University',      university_abbr:'APU',       university_location:'Bukit Jalil, Kuala Lumpur' },
  { id:17, university_id:10, name:'Bachelor of Cybersecurity',             level:'bachelor', duration_years:3, tuition_per_year:27000, field:'Technology',    description:'Hands-on ethical hacking, network security, and digital forensics in purpose-built cyber labs.',   intake:'Feb, Jul, Sep',university_name:'Asia Pacific University',      university_abbr:'APU',       university_location:'Bukit Jalil, Kuala Lumpur' },
  { id:18, university_id:11, name:'Bachelor of Computer Science',          level:'bachelor', duration_years:3, tuition_per_year:16000, field:'Technology',    description:"Affordable, high-quality CS degree with a strong alumni network in Malaysia's tech industry.",    intake:'Feb, Jun, Oct',university_name:'Universiti Tunku Abdul Rahman', university_abbr:'UTAR',      university_location:'Kampar, Perak' },
  { id:19, university_id:12, name:'Bachelor of Culinary Arts',             level:'bachelor', duration_years:3, tuition_per_year:36000, field:'Hospitality',   description:"Asia's best culinary arts school with professional kitchens and international chef mentors.",       intake:"Feb, Jul",     university_name:"Taylor's University",         university_abbr:"TAYLOR'S",  university_location:'Subang Jaya, Selangor' },
  { id:20, university_id:12, name:'Bachelor of Laws (LLB)',                level:'bachelor', duration_years:3, tuition_per_year:34000, field:'Law',           description:'Highly regarded law programme with mooting, internship placements and UK-validated recognition.', intake:'Feb, Jul',     university_name:"Taylor's University",         university_abbr:"TAYLOR'S",  university_location:'Subang Jaya, Selangor' },
  { id:21, university_id:13, name:'Bachelor of Business (Accounting)',     level:'bachelor', duration_years:3, tuition_per_year:28000, field:'Business',      description:'Lancaster University-affiliated degree with strong ACCA-exemption pathways.',                     intake:'Feb, Jul, Sep',university_name:'Sunway University',            university_abbr:'SUNWAY',    university_location:'Subang Jaya, Selangor' },
  { id:22, university_id:13, name:'Bachelor of Medicine (MBBS)',           level:'bachelor', duration_years:5, tuition_per_year:48000, field:'Medicine',      description:'A fully accredited medical programme with clinical training at Sunway Medical Centre.',           intake:'Feb',          university_name:'Sunway University',            university_abbr:'SUNWAY',    university_location:'Subang Jaya, Selangor' },
  { id:23, university_id:26, name:'Bachelor of Engineering (Petroleum)',   level:'bachelor', duration_years:4, tuition_per_year:42000, field:'Engineering',   description:'UK degree with strong ties to the oil & gas industry — PETRONAS and Shell partnerships.',       intake:'Feb, Sep',     university_name:'Heriot-Watt University Malaysia',university_abbr:'HWU',    university_location:'Putrajaya' },
  { id:24, university_id:26, name:'Bachelor of Business Management',       level:'bachelor', duration_years:4, tuition_per_year:38000, field:'Business',      description:"Same Heriot-Watt UK degree, earned in Malaysia for a fraction of Edinburgh's costs.",           intake:'Feb, Sep',     university_name:'Heriot-Watt University Malaysia',university_abbr:'HWU',    university_location:'Putrajaya' },
];

export const INSTITUTES: Institute[] = [
  {
    id: 1,
    abbr: 'BIGBEN',
    name: 'Big Ben Education Group',
    type: 'language',
    location: 'Kuala Lumpur',
    color: '#1D4ED8',
    description: 'English language, IELTS preparation, and education pathway support for students preparing to study in Malaysia.',
    website: 'https://www.bigben.edu.my',
    domain: 'bigben.edu.my',
    tuition_min: 0,
    tuition_max: 0,
    established: null,
    students_count: 0,
  },
  {
    id: 2,
    abbr: 'BRIGHT',
    name: 'Bright Language Center',
    type: 'language',
    location: 'Kuala Lumpur',
    color: '#F59E0B',
    description: 'English language centre in Malaysia offering practical English programmes for international learners.',
    website: 'https://bright.edu.my',
    domain: 'bright.edu.my',
    tuition_min: 0,
    tuition_max: 0,
    established: null,
    students_count: 0,
  },
  {
    id: 3,
    abbr: 'EMS',
    name: 'EMS Language Centre',
    type: 'language',
    location: 'Kuala Lumpur',
    color: '#10B981',
    description: 'English courses, placement support, and intensive language programmes for international learners.',
    website: 'https://ems.edu.my',
    domain: 'ems.edu.my',
    tuition_min: 0,
    tuition_max: 0,
    established: 2011,
    students_count: 0,
  },
  {
    id: 4,
    abbr: 'ELEC',
    name: 'ELEC Language Center',
    type: 'language',
    location: 'Kuala Lumpur',
    color: '#2563EB',
    description: 'English language school in Kuala Lumpur with intensive courses and student support services.',
    website: 'https://elec.edu.my',
    domain: 'elec.edu.my',
    tuition_min: 0,
    tuition_max: 0,
    established: null,
    students_count: 0,
  },
  {
    id: 5,
    abbr: 'SHEFFIELD',
    name: 'Sheffield Academy',
    type: 'training',
    location: 'Kuala Lumpur',
    color: '#7C3AED',
    description: 'Kuala Lumpur academy offering English programmes and training pathways for students and professionals.',
    website: 'https://sheffield.edu.my',
    domain: 'sheffield.edu.my',
    tuition_min: 0,
    tuition_max: 0,
    established: 2010,
    students_count: 0,
  },
  {
    id: 6,
    abbr: 'British Council',
    name: 'British Council Malaysia',
    type: 'language',
    location: 'Kuala Lumpur',
    color: '#4F6BFF',
    description: 'English language testing, IELTS preparation, and academic English support for international students.',
    website: 'https://www.britishcouncil.my',
    domain: 'britishcouncil.org',
    tuition_min: 0,
    tuition_max: 0,
    established: 1948,
    students_count: 0,
  },
  {
    id: 7,
    abbr: 'ELS',
    name: 'ELS Language Centres Malaysia',
    type: 'language',
    location: 'Kuala Lumpur',
    color: '#7B61FF',
    description: 'English pathway programmes and language preparation for students planning to study in Malaysia.',
    website: 'https://www.els.edu.my',
    domain: 'els.edu.my',
    tuition_min: 0,
    tuition_max: 0,
    established: 1990,
    students_count: 0,
  },
];
