import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import StudyPlanShell from '../layouts/StudyPlanShell';
import StudyPlanUniversityCard from '../components/StudyPlanUniversityCard';
import StudyPlanIcon from '../components/StudyPlanIcon';
import { useStudyPlan } from '../hooks/StudyPlanContext';
import { getStudyPlanResult } from '../services/studyPlanService';
import type { StudyPlanResult, StudyPlanUniversity } from '../types';
import { budgetOptions, englishOptions, labelFor, programOptions, qualificationOptions } from '../data/options';
import { trackStudyPlanEvent } from '../utils/analytics';
import { openStudyPlanWhatsApp } from '../utils/contact';

export default function StudyPlanResultPage() {
  const { profile } = useStudyPlan(); const [result,setResult]=useState<StudyPlanResult|null>(null); const [failed,setFailed]=useState(false); const [sticky,setSticky]=useState(true);
  useEffect(()=>{getStudyPlanResult(profile).then(setResult).catch(()=>setFailed(true));trackStudyPlanEvent('study_plan_result_viewed');},[profile]);
  useEffect(()=>{const target=document.getElementById('study-plan-review');if(!target)return;const observer=new IntersectionObserver(([entry])=>setSticky(!entry.isIntersecting),{threshold:.15});observer.observe(target);return()=>observer.disconnect();},[result]);
  const contact=(source:string,intent:string,university?:StudyPlanUniversity)=>{trackStudyPlanEvent('study_plan_contact_clicked',{source,intent,universityId:university?.universityId});openStudyPlanWhatsApp(profile,{source,intent,universityId:university?.universityId,programId:university?.programId});};
  if(failed)return <StudyPlanShell><section className="sp-empty"><StudyPlanIcon name="message" size={32}/><h1>ما قدرنا نطلع نتيجة دقيقة للحين</h1><p>بعض بيانات حالتك تحتاج مراجعة بشرية قبل ما نعطيك خيارات غير دقيقة.</p><button className="sp-button" onClick={()=>contact('result_error','human_review')}>خل NajmUni يراجع حالتي</button></section></StudyPlanShell>;
  if(!result)return <StudyPlanShell><div className="sp-loading"><div><span className="sp-loader-mark"><StudyPlanIcon name="route" size={28}/></span><h1>نرتب بياناتك</h1><p>نراجع المسارات المتوفرة ونجهز خطتك</p><i/></div></div></StudyPlanShell>;
  const englishText=labelFor(englishOptions,profile.english.type); const documents=['جواز السفر','شهادة الثانوية','كشف الدرجات','صورة شخصية','شهادة اللغة إن وجدت','مستندات إضافية حسب الجامعة'];
  const chips=[labelFor(qualificationOptions,profile.qualification),profile.grade!==null?`${profile.grade}%`:'المعدل غير محدد',labelFor(programOptions,profile.program),englishText,labelFor(budgetOptions,profile.budget)];
  return <StudyPlanShell><div className="sp-result">
    <header className="sp-report-header"><span className="sp-kicker">NajmUni Study Plan</span><h1>خطتك الدراسية</h1><p>رتبنا لك الصورة بناءً على البيانات اللي أدخلتها.</p><div className="sp-chips">{chips.map(chip=><span key={chip}>{chip}</span>)}</div></header>
    <section className="sp-readiness"><div className="sp-readiness-summary"><span className="sp-icon-box"><StudyPlanIcon name="activity" size={28}/></span><div><span>جاهزيتك الحالية</span><h2>{result.readiness.title}</h2><p>{result.readiness.note}</p><small>هذا مؤشر مبدئي، وليس نسبة قبول أو ضمانًا للقبول.</small></div></div><div className="sp-readiness-grid">{result.readiness.breakdown.map(item=><article key={item.label} className={item.tone}><StudyPlanIcon name={item.icon}/><span>{item.label}</span><strong>{item.value}</strong></article>)}</div></section>
    <section className="sp-result-section"><div className="sp-section-heading"><span>موعد البداية</span><h2>موعد الـIntake الأنسب لك</h2></div><div className="sp-intake-card"><StudyPlanIcon name="calendar" size={28}/><div><span>{result.recommendedIntake.title}</span><h3>{result.recommendedIntake.date}</h3><p>{result.recommendedIntake.note}</p></div><button className="sp-button-ghost" onClick={()=>contact('intake_card','verify_intake')}>أكد الموعد مع نجم</button></div></section>
    {result.studyPaths.map(path=><section className="sp-result-section" key={path.id}><div className="sp-path-title"><span>المسار الأقرب لحالتك</span><h2>{path.title}</h2><p>{path.description}</p></div>{path.universities.length?<div className="sp-university-grid">{path.universities.map(university=><StudyPlanUniversityCard key={university.programId} university={university} onContact={()=>contact('university_card','verify_university',university)}/>)}</div>:<div className="sp-safe-state">ما عندنا برامج كافية في السجل لهذا الاختيار. فريق نجم يقدر يراجع خيارات إضافية بدقة.</div>}</section>)}
    <section className="sp-two-column"><article className="sp-info-card"><span className="sp-icon-box"><StudyPlanIcon name="language"/></span><h2>وضع اللغة</h2><h3>{englishText}</h3><p>بعض الجامعات قد توفر مسارات أو خيارات مختلفة حسب البرنامج.</p><button className="sp-button-ghost" onClick={()=>contact('english_card','review_english_options')}>راجع خيارات اللغة مع نجم</button></article><article className="sp-info-card"><span className="sp-icon-box"><StudyPlanIcon name="file"/></span><h2>المستندات اللي تحتاج تجهزها</h2><ul>{documents.map((document,index)=><li key={document}><StudyPlanIcon name="check" size={15}/><span>{document}{index>3&&<small>قد يُطلب</small>}</span></li>)}</ul><p>القائمة إرشادية وقد تختلف حسب الجامعة والبرنامج.</p></article></section>
    <section className="sp-result-section"><div className="sp-section-heading"><span>خطوات عملية</span><h2>خطواتك الجاية</h2></div><div className="sp-timeline">{result.actionPlan.map(item=><article key={item.when}><b><StudyPlanIcon name={item.icon}/></b><div><span>{item.when}</span><p>{item.action}</p></div></article>)}</div></section>
    <section className="sp-guide-card"><div className="sp-guide-icon"><StudyPlanIcon name="file" size={30}/></div><div><span>ملف عملي للطالب</span><h2>خذ ملف التجهيز للدراسة في ماليزيا</h2><p>جهزنا لك ملف مختصر يساعدك تعرف أهم الخطوات والمستندات والتكاليف اللي تحتاج تنتبه لها قبل بداية الدراسة.</p><ul><li>خطوات التقديم وترتيب الإجراءات</li><li>المستندات وأخطاء تأخر الملفات</li><li>اللغة والتكاليف ومرحلة Student Pass</li><li>Checklist قبل السفر وأول أيامك في ماليزيا</li></ul></div><button className="sp-button" onClick={()=>contact('free_guide','request_free_guide')}>أرسل لي ملف التجهيز</button></section>
    <section className="sp-final-cta" id="study-plan-review"><StudyPlanIcon name="message" size={30}/><h2>راجع خطتك مع نجم</h2><p>خل فريق نجم يراجع معك الخيارات اللي ظهرت لك ويتأكد من القبول، الرسوم، الـIntake والخطوة الجاية.</p><div><button className="sp-button" onClick={()=>contact('final_review','review_study_plan')}>راجع خطتي مع نجم</button></div></section>
    <Link to="/study-plan/questions" className="sp-edit-link">تعديل بيانات الخطة</Link>
  </div>{sticky&&<div className="sp-mobile-sticky"><button onClick={()=>contact('mobile_sticky','review_study_plan')}>راجع خطتك مع نجم</button></div>}</StudyPlanShell>;
}
